name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Main branch par push hone par workflow trigger hoga
  workflow_dispatch: # Manual trigger ka option

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Streamlit ke compatible Python version ka use karein

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit App
      run: |
        streamlit run your_app.py --server.headless true
